"""add users table

Revision ID: 1d1274993392
Revises: 
Create Date: 2025-03-04 16:13:24.365381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d1274993392'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('lancamento')
    op.drop_table('categoria')
    op.drop_table('contato')
    op.drop_table('conta')
    op.drop_table('cliente')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_empresarial', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=False),
    sa.Column('ie', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('estado', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False)
    )
    op.create_table('cliente',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cliente_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_empresarial', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=False),
    sa.Column('ie', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('estado', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('nota', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cliente_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('conta',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conta_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agencia', sa.VARCHAR(length=18), autoincrement=False, nullable=False),
    sa.Column('conta_corrente', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('data_inclusao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False),
    sa.UniqueConstraint('id', name='conta_id_unique'),
    postgresql_ignore_search_path=False
    )
    op.create_table('contato',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('departamento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], name='contato_id_cliente_fkey'),
    sa.PrimaryKeyConstraint('id', name='contato_pkey')
    )
    op.create_table('categoria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_empresarial', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False),
    sa.Column('debito', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('credito', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id_conta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id'], name='categoria_id_conta_fkey'),
    sa.PrimaryKeyConstraint('id', name='categoria_pkey')
    )
    op.create_table('lancamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parcela', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_parcela', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('data_lancamento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('situacao', postgresql.ENUM('ativo', 'inativo', name='situacao'), autoincrement=False, nullable=False),
    sa.Column('id_conta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_fornecedor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['conta.id'], name='lancamento_id_categoria_fkey'),
    sa.ForeignKeyConstraint(['id_conta'], ['conta.id'], name='lancamento_id_conta_fkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
